INSERT INTO hats (id, name, description, image_path, price) VALUES (0, 'Summer Beach Sun Hat', 'Made of knitted lace ribbon with fabric material 100% cotton and sweatband inside helps to keep head cool.','sun-hat.jpg',34);
INSERT INTO hats (id, name, description, image_path, price) VALUES (1, 'Queenfur Knit Slouchy Beanie', 'The cable-knit hat is made of 100% soft Acrylic, with faux fur pompom on the top of the hat which is thick and comfortable. Can make you feel warm and fashion.', 'Beanie.jpg', 19);
INSERT INTO hats (id, name, description, image_path, price) VALUES (2, 'Bamboo Fashion Hat', 'The Bamboo Hat is pretied and requires no tying, just slip it on & off you go. Stretches to fit most head sizes.', 'bamboo-hat.jpg', 24);
INSERT INTO hats (id, name, description, image_path, price) VALUES (3, 'Fedora Hat', 'The shape of this hat falls effortlessly into place with grace.Wide brim hats make a stunning fashion statement, that can be worn with casual or formal attire.', 'Fedora Hat.jpg', 19);
INSERT INTO hats (id, name, description, image_path, price) VALUES (4, 'Wide Brim Sun Hat', 'Made of Eco-friendly Recycled paper. Breathable and comfortable. Tightly woven for the quality and durability. Strong Anti-uv Function, UPF 50+', 'Wide Brim Sun Hat.jpg', 34);
INSERT INTO hats (id, name, description, image_path, price) VALUES (5, 'Featherlight Sports Hat', 'The SAAKA Hat is designed to be unstructured unlike most hats which are firm and stiff. Our hat is completely flexible and never feels hard while being worn.', 'Featherlight Sports Hat.jpg', 35);
INSERT INTO hats (id, name, description, image_path, price) VALUES (6, 'Sun Visor Hat', 'Sun Visor Straw Hat for women with wide brim is made of high quality paper straw, gives you great sun protection all over the face and neck and the neutral colors go with everything.', 'Sun Visor Hat.jpg', 35);
INSERT INTO hats (id, name, description, image_path, price) VALUES (7, 'Cute Bucket Hat', 'Funny ocean multicolored pattern all over this bucket hat, makes you more attractive and charming the crowd. It is great for travel, beach, vacation, trip, outdoor activities, street strolling, fishing for the sun protection headwear.', 'Cute Bucket Hat.jpg', 20);
INSERT INTO hats (id, name, description, image_path, price) VALUES (8, 'Summer Sun Hat', 'If you looking for style and sun protection,this is the visor for you.It is very comfortable,5.1” wide brim provides excellent sun protection.The curved visor offers extra protection for your face and eyes from harmful sun rays.', 'Summer Sun Hat.jpg', 24);

INSERT INTO belts (id, name, description, image_path, price) VALUES(0, 'JasGood Leather Waist Belt','JASGOOD JA018 Women Wide Belt made of genuine cowhide leather that touch so soft and durable. High quality at bottom low price.','JasGood Leather Waist Belt.jpg', 25);
INSERT INTO belts (id, name, description, image_path, price) VALUES(1, 'Fashion Wide Belt Braided Leatherette','High stretchy, Braided leatherette, Wide elastic waist belt, Golden hook buckle fastening.', 'Fashion Wide Belt Braided Leatherette.jpg', 24);
INSERT INTO belts (id, name, description, image_path, price) VALUES(2,'Fairwin Elastic Braided Belt','We choose the blends of 60% mulberry silk and 40% polyester as the main fabric of elastic belt, which is rich in elasticity and breathable, has smooth tactility, and proves its distinctive and exquisite quality different from other braided belt.', 'Fairwin Elastic Braided Belt.jpg', 32);
INSERT INTO belts (id, name, description, image_path, price) VALUES(3, 'Suyi Stretchy Rhinestone Belt','This rhinestone belt the front part is made of high-quality leather and shiny rhinestones, and the back part is made of soft and comfortable elastic fabric, the crystal elastic belts will let you feel more relaxed and comfortable.', 'Suyi Stretchy Rhinestone Belt.jpg', 27);
INSERT INTO belts (id, name, description, image_path, price) VALUES(4, 'Glamorstar Chain Belt', 'This chain rhinestone belt is made of high quality metal alloy. Rhinestones on the belt make you more elegant and radiant in the crowd.', 'Glamorstar Chain Belt.jpg', 24);
INSERT INTO belts (id, name, description, image_path, price) VALUES(5,'Timberland Leather Belt','The Timberland leather belt for women is made with 100% genuine leather and is the perfect belt for daily use.','Timberland Leather Belt.jpg', 40);
INSERT INTO belts (id, name, description, image_path, price) VALUES(6,'Vintage Western Leather Belt','This belt can be trimmed easily without any damage to the belt. This vintage leather belt is a quite good gift-giving experience.', 'Vintage Western Leather Belt.jpg',27);
INSERT INTO belts (id, name, description, image_path, price) VALUES(7,'Chic Belts for Jeans', 'We choose high-quality PU leather as the raw materials,which makes this women belt not only durable but also soft to touch,without any overly decorations,simple solid color,unique golden arc pin buckle design,beautiful intellectual women always wear it on the hips with jeans or on the waist to cinch a dress or skirt.', 'Chic Belts for Jeans.jpg', 37);
INSERT INTO belts (id, name, description, image_path, price) VALUES(8,'Double Grommets Belt', 'The casual style of the Canvas Belt makes it the right fit for every occasion.', 'Double Grommets Belt.jpg', 20);

INSERT INTO dresses (id, name, description, image_path, price) VALUES (0, 'Summer Dress', 'Midi-length dress in Stretch fabric, super comfortable to wear. Short sleeve, knee length, wrap front, low-cut v-neck, A-line, pretty flower/leopard/stripes printed, with two side pockets for your essentials.', 'Summer Dress.jpg', 56);
INSERT INTO dresses (id, name, description, image_path, price) VALUES (1, 'Halter Sleeveless Mermaid Dress', 'Cute Halter Neck, Sleeveless, Solid, Racer Front Design Zipper Closure at the Dress Back. Chic and Formal Style, Mermaid Silhouette, Floor-length, Long Evening Dress, Vintage and Classy.', 'Halter Sleeveless Mermaid Dress.jpg', 58);
INSERT INTO dresses (id, name, description, image_path, price) VALUES (2, 'Cocktail Dress', 'Delicate lace accents this figure-flattering A-line cocktail dress for a touch of elegant style, which will bring you captivating elegance wherever you go.', 'Cocktail Dress.jpg', 85);
INSERT INTO dresses (id, name, description, image_path, price) VALUES (3, 'Lyla Plunging Dress', 'Thick material. Perfect quality. Zipper closure. 97% Polyester, 3% Spandex.', 'Lyla Plunging Dress.jpg', 145);
INSERT INTO dresses (id, name, description, image_path, price) VALUES (4, 'Summer V Neck Short Ruffles Dress', 'Womens tiered mini dress designed with lantern sleeves with elastic cuff,split neck and flowy hem.', 'Summer V Neck Short Ruffles Dress.jpg', 43);
INSERT INTO dresses (id, name, description, image_path, price) VALUES (5, 'Petite Cocktail Dress', 'Pull On closure. Perfect for special occasions or evening parties. Dry clean only.', 'Petite Cocktail Dress.jpg', 204);
INSERT INTO dresses (id, name, description, image_path, price) VALUES (6, 'Summer Casual Dress', 'Summer Bodycon Dress Is Crafted In a Stretchy Knit with a Crewneck and Short Sleeves. With Butterfly Straps On Waist Design To Modify Your Body Lines.', 'Summer Casual Dress.jpg', 42);

INSERT INTO shoes (id, name, description, image_path, price) VALUES (0, 'Satin Rhinestone Tango Shoes', 'This classical dance shoes are made of high quality satin upper,smooth and exquisite,covered with colorful rhinestones,very sparkly.', 'Satin Rhinestone Tango Shoes.jpg', 60);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (1, 'Women High Heel Shoes', 'A mixture of vintage and modern aesthetics meld in these shoes. These heels come well packaged, with inserts inside the shoes.', 'Womens High Heel Shoes.jpg', 55);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (2, 'Clarks Womens Ambyr Joy Pump', 'Ortholite Footbed, Smooth Textile Linings, Durable TPR Outsole. Heel measures approximately 3.46". Comfortable Heel Height', 'Clarks Womens Ambyr Joy Pump.jpg', 100);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (3, 'Closed Toe Chunky Wedding Shoes', 'Adjustable buckle closures. Latex padded insole for added comfort. Thermoplastic Elastomers sole.', 'Closed Toe Chunky Wedding Shoes.jpg', 54);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (4, 'Steve Madden Shoes', 'Patent leather or printed PU upper material. Shaft measures approximately not_applicable from arch. Steve Madden. Comfortable and Sexy.', 'Steve Madden Shoes.jpg', 230);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (5, 'Aachcol Women Shoes' ,'Designed with a classic and elegant round-toe Stiletto heels, must-haves in your wardrobe. Designed for mature lady in both casual and formal occasions.', 'Aachcol Women Shoes.jpg', 73);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (6, 'Taimi Dress Sandal', 'Distinctly gorgeous shoes, impeccably crafted for a better fit and feel, all day. Leather sole. N5 comfort.', 'Taimi Dress Sandal.jpg', 112);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (7, 'Linvale Sea Fashion Boot', 'Comfort Features: Ortholite Footbed, Smooth Textile Linings, Durable Composition Rubber Outsole.', 'Linvale Sea Fashion Boot.jpg', 330);
INSERT INTO shoes (id, name, description, image_path, price) VALUES (8, 'Rinela Woven High Heel Sandals', 'Brinela combines these trends atop an open square toe and padded footbed anchored on a flared high heel.', 'Rinela Woven High Heel Sandals.jpg', 135);