INSERT INTO hats (id, name, description, image_path, price) VALUES (0, 'Summer Beach Sun Hat', 'Made of knitted lace ribbon with fabric material 100% cotton and sweatband inside helps to keep head cool.','sun-hat.jpg',34);
INSERT INTO hats (id, name, description, image_path, price) VALUES (1, 'Queenfur Knit Slouchy Beanie', 'The cable-knit hat is made of 100% soft Acrylic, with faux fur pompom on the top of the hat which is thick and comfortable. Can make you feel warm and fashion.', 'Beanie.jpg', 19);
INSERT INTO hats (id, name, description, image_path, price) VALUES (2, 'Bamboo Fashion Hat', 'The Bamboo Hat is pretied and requires no tying, just slip it on & off you go. Stretches to fit most head sizes.', 'bamboo-hat.jpg', 24);
INSERT INTO hats (id, name, description, image_path, price) VALUES (3, 'Fedora Hat', 'The shape of this hat falls effortlessly into place with grace.Wide brim hats make a stunning fashion statement, that can be worn with casual or formal attire.', 'Fedora Hat.jpg', 19);
INSERT INTO hats (id, name, description, image_path, price) VALUES (4, 'Wide Brim Sun Hat', 'Made of Eco-friendly Recycled paper. Breathable and comfortable. Tightly woven for the quality and durability. Strong Anti-uv Function, UPF 50+', 'Wide Brim Sun Hat.jpg', 34);
INSERT INTO hats (id, name, description, image_path, price) VALUES (5, 'Featherlight Sports Hat', 'The SAAKA Hat is designed to be unstructured unlike most hats which are firm and stiff. Our hat is completely flexible and never feels hard while being worn.', 'Featherlight Sports Hat.jpg', 35);
INSERT INTO hats (id, name, description, image_path, price) VALUES (6, 'Sun Visor Hat', 'Sun Visor Straw Hat for women with wide brim is made of high quality paper straw, gives you great sun protection all over the face and neck and the neutral colors go with everything.', 'Sun Visor Hat.jpg', 35);
INSERT INTO hats (id, name, description, image_path, price) VALUES (7, 'Cute Bucket Hat', 'Funny ocean multicolored pattern all over this bucket hat, makes you more attractive and charming the crowd. It is great for travel, beach, vacation, trip, outdoor activities, street strolling, fishing for the sun protection headwear.', 'Cute Bucket Hat.jpg', 20);
INSERT INTO hats (id, name, description, image_path, price) VALUES (8, 'Summer Sun Hat', 'If you looking for style and sun protection,this is the visor for you.It is very comfortable,5.1” wide brim provides excellent sun protection.The curved visor offers extra protection for your face and eyes from harmful sun rays.', 'Summer Sun Hat.jpg', 24);

INSERT INTO belts (id, name, description, image_path, price) VALUES(0, 'JasGood Leather Waist Belt','JASGOOD JA018 Women Wide Belt made of genuine cowhide leather that touch so soft and durable. High quality at bottom low price.','JasGood Leather Waist Belt.jpg', 25);
INSERT INTO belts (id, name, description, image_path, price) VALUES(1, 'Fashion Wide Belt Braided Leatherette','High stretchy, Braided leatherette, Wide elastic waist belt, Golden hook buckle fastening.', 'Fashion Wide Belt Braided Leatherette.jpg', 24);
INSERT INTO belts (id, name, description, image_path, price) VALUES(2,'Fairwin Elastic Braided Belt','We choose the blends of 60% mulberry silk and 40% polyester as the main fabric of elastic belt, which is rich in elasticity and breathable, has smooth tactility, and proves its distinctive and exquisite quality different from other braided belt.', 'Fairwin Elastic Braided Belt.jpg', 32);
INSERT INTO belts (id, name, description, image_path, price) VALUES(3, 'Suyi Stretchy Rhinestone Belt','This rhinestone belt the front part is made of high-quality leather and shiny rhinestones, and the back part is made of soft and comfortable elastic fabric, the crystal elastic belts will let you feel more relaxed and comfortable.', 'Suyi Stretchy Rhinestone Belt.jpg', 27);
INSERT INTO belts (id, name, description, image_path, price) VALUES(4, 'Glamorstar Chain Belt', 'This chain rhinestone belt is made of high quality metal alloy. Rhinestones on the belt make you more elegant and radiant in the crowd.', 'Glamorstar Chain Belt.jpg', 24);
INSERT INTO belts (id, name, description, image_path, price) VALUES(5,'Timberland Leather Belt','The Timberland leather belt for women is made with 100% genuine leather and is the perfect belt for daily use.','Timberland Leather Belt.jpg', 40);
INSERT INTO belts (id, name, description, image_path, price) VALUES(6,'Vintage Western Leather Belt','This belt can be trimmed easily without any damage to the belt. This vintage leather belt is a quite good gift-giving experience.', 'Vintage Western Leather Belt.jpg',27);
INSERT INTO belts (id, name, description, image_path, price) VALUES(7,'Chic Belts for Jeans', 'We choose high-quality PU leather as the raw materials,which makes this women belt is not only durable but also soft to touch,without any overly decorations,simple and clear solid color,unique golden arc pin buckle design,beautiful intellectual women always wear it on the hips with jeans or on the waist to cinch a dress or skirt,because it is a simple way to compliment your figure.', 'Chic Belts for Jeans.jpg', 37);
INSERT INTO belts (id, name, description, image_path, price) VALUES(8,'Double Grommets Belt', 'The casual style of the Canvas Belt makes it the right fit for every occasion.', 'Double Grommets Belt.jpg', 20);