DROP TABLE IF EXISTS hats CASCADE;
DROP TABLE IF EXISTS belts CASCADE;
DROP TABLE IF EXISTS dresses CASCADE;
DROP TABLE IF EXISTS shoes CASCADE;


CREATE TABLE hats (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_path VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE belts (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_path VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE dresses (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_path VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE shoes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_path VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0
);

